package web

// https://githubhelp.com/arsmn/fiber-swagger

import (
	"github.com/gofiber/fiber/v2"

	swagger "github.com/arsmn/fiber-swagger/v2"
	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually "github.com/username/reponame/docs"
	//_ "github.com/arsmn/fiber-swagger/v2/example/docs"
	_ "github.com/nbigot/ministream/docs"
)

// SwaggerRoute func for describe group of API Docs routes.
func AddSwaggerRoute(a *fiber.App) {

	// url example: http://127.0.0.1:8080/swagger/index.html
	// url example: https://localhost:4343/index.html

	// Create routes group.
	//route := a.Group("/swagger")
	route := a.Group("/")

	// Routes for GET method:
	route.Get("*", swagger.HandlerDefault)     // default
	route.Get("*", swagger.New(swagger.Config{ // custom
		URL:         "/swagger/doc.json",
		DeepLinking: false,
	}))
}
